### ISSUE TITLE
Load scripts from modules

### ISSUE THREAD

**Issue by ricklupton** [probs-lab/probs-runner#7]
Scripts can be loaded from two sources:

1. From a folder
2. From installed Python packages

If you specify a folder `script_source_dir` to load from, the files should be arranged like this:

- *script_source_dir*
    - *module name 1*
        - `scripts`
            - `master.rdfox`
            - ...
        - `data` (optional) 
    - *module name 2*
    - ...

For example, you could clone all the module repositories you wanted to use into a single folder, and pass that as `script_source_dir`.

If loading from Python packages, probs-runner will try to access the data files of a Python package called `probs-module-<module name>`, which should contain:

- `scripts`
    - `master.rdfox`
    - ...
- `data` (optional) 

The probs-module code that sets up the input files for RDFox needs to be updated to expect this file structure.

(Previously it was arranged as `script_source_dir / scripts / <module-name> / ...` and everything is loaded from a single Python package)

- [x] Update the code as above
- [x] Copy a description like the one above into the README file to describe how scripts are loaded
- [x] Test both methods of loading scripts:
    - [x] By using the environment variable "PROBS_SCRIPT_SOURCE_DIR" (https://github.com/probs-lab/probs-runner/blob/updated-scripts-layout/tests/conftest.py#L11) to load local copies of the modules
    - [x] By installing the Python packages from the modules into the active Python environment 
    - [x] Describe how to run the tests in both of these ways in https://github.com/probs-lab/probs-runner/blob/updated-scripts-layout/DEVELOPING.md#tests

**Comment by ricklupton** [comment]
After moving to modules, this might be slightly out of date (`PROBS_SCRIPT_SOURCE_DIR` --> `PROBS_MODULE_PATH`).

The goal is to
- Make sure the way that it works is described somewhere (in the README or docs)
- Both ways (installed Python packages, and from a specified path) can be tested

As the next step can you look at what the docs/README/tests currently say to check if they need further changes?

**Comment by stephenjboyle** [comment]
@ricklupton 
Some of the data conversion tests are failing for https://github.com/probs-lab/probs-runner/blob/master/tests/test_probs_runner.py : ```test_convert_data_csv```, ```test_convert_data_ttl_from_dir``` and ```test_convert_data_ttl_directly```.  File ```probs_original_data.nt.gz``` is being created correctly by the conversion in data folder in the working dir, but this is not being copied to ```output.nt.gz``` (which is 0 bytes). 
The test ```test_convert_data_large_data_size``` which works in the same way (but uses a large csv data file) works correctly. 
If you modify https://github.com/probs-lab/probs-runner/blob/master/tests/sample_datasource_simple/data.csv to add extra data lines (I added another 10,000)  then the test ```test_convert_data_csv``` passes. 
Tests for enhancement are passing.
Using rdfox version 6.3.1. - will try other versions.

**Comment by ricklupton** [comment]
@stephenjboyle I think this is a problem that happens occasionally when writing gzipped files. RDFox seems to delegate the compression of the output file to a separate gzip process, and so it can happen that RDFox exits before the compressed data has finished being written. probs-runner only has a relationship to RDFox itself, so as far as I know, there's not a robust way to wait for the gzip process to complete before exiting.

If you can reproduce this reliably, as a workaround, does inserting a `time.sleep(0.01)` (or other delay) before this line help? https://github.com/probs-lab/probs-runner/blob/ab72c6618638249b29ee204e1aced62628871146/src/probs_runner/runners.py#L309

@stefanogermano would this be something you could pass onto OST? I would like RDFox not to exit until its subprocess gzip has finished and its output files are actually written. (I think this is what is happening, but I'm not sure how to prove it).

**Comment by stephenjboyle** [comment]
@ricklupton 
The problem seems to occur intermittently :- I added the sleep function and the tests passed, but then when I removed the sleep function (to confirm that is what cured it) the tests still passed nearly all the time apart from once. Yesterday it seemed to be happening most of the time.

**Comment by stefanogermano** [comment]
> @stefanogermano would this be something you could pass onto OST? I would like RDFox not to exit until its subprocess gzip has finished and its output files are actually written. (I think this is what is happening, but I'm not sure how to prove it).

As documented here
https://github.com/probs-lab/ukfires-probs-docs/discussions/345#discussioncomment-3224611
we have already mentioned this to them multiple times (and at the moment they do not seem interested in fixing it).

@stephenjboyle if you have a specific piece of code (as small and self consistent as possible, otherwise they will ask me to break it down) that we can send to them, I can deliver it.

**Comment by ricklupton** [comment]
> As documented here
> [probs-lab/ukfires-probs-docs#345 (comment)](https://github.com/probs-lab/ukfires-probs-docs/discussions/345#discussioncomment-3224611)
> we have already mentioned this to them multiple times (and at the moment they do not seem interested in fixing it).

Sorry, yes.

**Comment by ricklupton** [comment]
This is done now
