### ISSUE TITLE
Queries of endpoint using object_code and process_code failing

### ISSUE THREAD

**Issue by stephenjboyle** [probs-lab/probs-runner#9]
For RDF using new ontology with :codeName and :processName replaced with rdfs:label, queries of endpoint by object_code and
process_code fail. 
https://github.com/probs-lab/probs-runner/blob/updated-scripts-layout/src/probs_runner/endpoint.py 
and
https://github.com/probs-lab/probs-runner/blob/updated-scripts-layout/tests/test_probs_endpoint.py
need modifying to reflect this change in ontology.

**Comment by ricklupton** [comment]
Closed by #10
